export const intitialRoutine = {
  days: {
    sunday: [{ title: "Sunday Workout", exercises: [] }],
    monday: [{ title: "Monday Workout", exercises: [] }],
    tuesday: [{ title: "Tuesday Workout", exercises: [] }],
    wednesday: [{ title: "Wednesday Workout", exercises: [] }],
    thursday: [{ title: "Thursday Workout", exercises: [] }],
    friday: [{ title: "Friday Workout", exercises: [] }],
    saturday: [{ title: "Saturday Workout", exercises: [] }],
  },
};

export const initialExercises = [
  {
    name: "Squats",
    type: "weight",
    sets: [],
    equipment: ["Barbell", "Squat Rack"],
  },
  {
    name: "Bench Press",
    type: "weight",
    sets: [],
    equipment: ["Barbell", "Bench"],
  },
  {
    name: "Bent Over Rows",
    type: "weight",
    sets: [],
    equipment: ["Barbell"],
  },
  {
    name: "Lunges",
    type: "weight",
    sets: [],
    equipment: ["Dumbbells"],
  },
  {
    name: "Deadlifts",
    type: "weight",
    sets: [],
    equipment: ["Barbell"],
  },
  {
    name: "Overhead Press",
    type: "weight",
    sets: [],
    equipment: ["Barbell"],
  },
  {
    name: "Bulgarian Split Squats",
    type: "weight",
    sets: [],
    equipment: ["Dumbbells"],
  },
  {
    name: "Planks",
    type: "timed",
    sets: [],
    equipment: [],
  },
  {
    name: "Leg Press",
    type: "weight",
    sets: [],
    equipment: ["Leg Press Machine"],
  },
  {
    name: "Hamstring Curls",
    type: "weight",
    sets: [],
    equipment: ["Leg Curl Machine"],
  },
  {
    name: "Calf Raises",
    type: "weight",
    sets: [],
    equipment: ["Calf Raise Machine"],
  },
  {
    name: "Dynamic Stretching Routine",
    type: "timed",
    sets: [],
    equipment: [],
  },
  {
    name: "Chest Flys",
    type: "weight",
    sets: [],
    equipment: ["Chest Fly Machine"],
  },
  {
    name: "Tricep Dips",
    type: "weight",
    sets: [],
    equipment: ["Parallel Bars"],
  },
  {
    name: "Cycling",
    type: "timed",
    sets: [],
    equipment: ["Bicycle"],
  },
  {
    name: "Running",
    type: "timed",
    sets: [],
    equipment: [],
  },
  {
    name: "Jump Rope",
    type: "timed",
    sets: [],
    equipment: ["Jump Rope"],
  },
  {
    name: "Yoga",
    type: "timed",
    sets: [],
    equipment: [],
  },
];
export const equipment = [
  "Barbell",
  "Bench",
  "Bicycle",
  "Dumbbells",
  "Pull-Up Bar",
  "Parallel Bars",
  "Squat Rack",
  "Leg Press Machine",
  "Leg Curl Machine",
  "Chest Fly Machine",
  "Calf Raise Machine",
  "Jump Rope",
  "Yoga Mat",
  "Yoga Blocks",
  "Yoga Strap",
];
